yaml 			= require 'js-yaml'
fs				= require 'fs'
child_process 	= require 'child_process'

module.exports =
	# ----- Generates Version includes for sass/coffee
	generateVersioningOutput: ( onComplete )->
		pkg = JSON.parse( fs.readFileSync( "package.json", 'utf8') )
		child_process.exec 'git rev-parse --short HEAD',(error,stdout,stderr)->
			version = pkg.version + "|" + stdout.replace("\n","") + "|coffee-number-" + Math.round(Math.random()*10000)
			versionQuery = "?v=" + version
			console.log('app version ' + version)

			coffeeOutput = "# Generated by Grunt task utils.coffee\nclass Version\n  @number:'" + version + "'\n  @query:'" + versionQuery + "'"
			#sassOutput = "// Generated by Grunt task utils.coffee\n$version: '" + version + "'\n$versionQuery: '" + versionQuery + "'"
			scssOutput = '// Generated by Grunt task utils.coffee\n$version: "' + version + '";\n$versionQuery: "' + versionQuery + '";'

			fs.writeFileSync "source/coffee/version.coffee", coffeeOutput
			fs.writeFileSync "source/scss/version.scss", scssOutput

			onComplete()